### ISSUE TITLE
Trying to use example

### ISSUE THREAD

**Issue by t5unamie** [Patreon/patreon-js#19]
When I check out the repo.
run npm install at the first level and then npm install inside example.

I then try to run npm start and get the following error.

```javascript
(function (exports, require, module, __filename, __dirname) { import { oauth, patreon } from '../dist/index.js'
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! patreon-examples@0.0.1 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
```

**Comment by t5unamie** [comment]
never mind worked it out. running "npm run-script examples" to get everything up and running. 

However all I have to say is WHY BABEL!. LOL! I cry inside trying to understand that.
